TOOLCHAIN_DIR := $(OUTPUT)/toolchain/$(ARCH)
CROSS_TRIPLET := $(ARCH)-unknown-textos
CROSS_COMPILE := $(TOOLCHAIN_DIR)/$(CROSS_TRIPLET)-

export TOOLCHAIN_DIR
export CROSS_TRIPLET
export CROSS_COMPILE

ifeq (${ARCH},x86_64)
  EFI_ARCH := X64
endif
